version: '3'
services:
  redis:
    image: "redis:3.2-alpine"
  geth:
    build: geth
    image: "geth"
    volumes:
      - gethblockchain:/data
  app:
    build: "tracker-app"
    image: "trackerapp"
    environment:
      - GETH_HOST=geth
      - GETH_PORT=8546
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - CONTRACT_ADDRESS=0x4870E705a3def9DDa6da7A953D1cd3CCEDD08573
      - START_BLOCK=3782416
  proxy:
    build: proxy
    image: proxy
    volumes:
      - /etc/letsencrypt/live/ws.moeda.in/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/ws.moeda.in/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "443:443"
volumes:
  gethblockchain:
    driver: local