version: '3'
services:
  redis:
    image: "redis:3.2-alpine"
    ports:
      - "6379:6379"
  geth:
    build: geth
    image: "geth"
    volumes:
      - /data
  app:
    build: "tracker-app"
    image: "trackerapp"
    environment:
      - GETH_HOST=geth
      - GETH_PORT=8546
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - CONTRACT_ADDRESS=0x4870E705a3def9DDa6da7A953D1cd3CCEDD08573
      - CONTRACT_TOPIC=0x12cb4648cf3058b17ceeb33e579f8b0bc269fe0843f3900b8e24b6c54871703c
    ports:
      - "3000:3000"